exclude: '^docs/conf.py'

default_install_hook_types: [pre-commit, commit-msg]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v6.0.0"
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=16384']
    - id: check-ast
    - id: check-case-conflict
    - id: check-illegal-windows-names
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: pretty-format-json
      args: ['--autofix']
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "v2.18.1"
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/codespell-project/codespell
  rev: "v2.4.2"
  hooks:
    - id: codespell
      stages: [commit-msg, pre-commit]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.15.6"
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/DetachHead/basedpyright-prek-mirror
  rev: "1.38.2"
  hooks:
    - id: basedpyright

- repo: https://github.com/gitleaks/gitleaks
  rev: "v8.24.2"
  hooks:
    - id: gitleaks

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: "v4.4.0"
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
